"""trivia_data = {

              "question": "In which series of games do you collect souls to empower you and buy weaponry and armor with?",
              "correct_answer": "Souls ",
              "incorrect_answers":
              "Final Fantasy ",
               "Monster Hunter",
             "The Legend of Zelda"


              "question": "In South Park, what is Stan's surname?",
              "correct_answer": "Marsh",
            "incorrect_answers":
               """ "Stotch"
                 "Broflovski", "Tweak"
             {"category": "Mythology", "type": "multiple", "difficulty": "medium",
              "question": "The Hippogriff, not to be confused with the Griffon, is a magical creature with the front half of an eagle, and the back half of what?",
              "correct_answer": "A Horse", "incorrect_answers": ["A Dragon", "A Tiger", "A Lion"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
              "question": "In World of Warcraft Lore, four Old Gods created a giant and powerful creature. What was it called? ",
              "correct_answer": "The Ancient One",
              "incorrect_answers": ["Anomalous", "Eater of Souls", "The Lich King"]},
             {"category": "Celebrities", "type": "multiple", "difficulty": "medium",
              "question": "What is Doug Walker&#039;s YouTube name?",
              "correct_answer": "The Nostalgia Critic",
              "incorrect_answers": ["The Angry Video Game Nerd", "AngryJoeShow",
                                    "The Cinema Snob"]},
             {"category": "Celebrities", "type": "multiple", "difficulty": "medium",
              "question": "Paul McCartney has always used his middle name. What is his real first name? ",
              "correct_answer": "James", "incorrect_answers": ["John", "Jack", "Justin"]},
             {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
              "question": "What was the title of the first Bond movie, released in 1962?",
              "correct_answer": "Dr. No",
              "incorrect_answers": ["From Russia with Love", "Goldfinger", "Thunderball"]},
             {"category": "Geography", "type": "multiple", "difficulty": "medium",
              "question": "All of the following countries have official claims to territory in Antartica EXCEPT:",
              "correct_answer": "United States",
              "incorrect_answers": ["Australia", "Chile", "Norway"]},
             {"category": "Geography", "type": "multiple", "difficulty": "medium",
              "question": "What African country has Portuguese as its official language?",
              "correct_answer": "Mozambique", "incorrect_answers": ["Botswana", "Gabon", "Togo"]},
             {"category": "History", "type": "multiple", "difficulty": "medium",
              "question": "In the War of the Pacific (1879 - 1883), Bolivia lost its access to the Pacific Ocean after being defeated by which South American country?",
              "correct_answer": "Chile", "incorrect_answers": ["Peru", "Brazil", "Argentina"]},
             {"category": "Animals", "type": "boolean", "difficulty": "easy",
              "question": "A bear does NOT defecate during hibernation. ", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "Geography", "type": "multiple", "difficulty": "hard",
              "question": "How many countries border Kyrgyzstan?", "correct_answer": "4",
              "incorrect_answers": ["3", "1", "6"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
              "question": "Gordon Freeman is said to have burnt and destroyed what food in the break room microwave?",
              "correct_answer": "Casserole",
              "incorrect_answers": ["Sub Sandwich", "Chicken Soup", "Pepperoni Pizza"]},
             {"category": "Entertainment: Cartoon & Animations", "type": "multiple",
              "difficulty": "hard",
              "question": "In the web-comic Homestuck, what is the name of the game the 4 kids play?",
              "correct_answer": "Sburb", "incorrect_answers": ["Homesick", "Husslie", "Hiveswap"]},
             {"category": "Entertainment: Books", "type": "multiple", "difficulty": "medium",
              "question": "The novel &quot;Of Mice And Men&quot; was written by what author? ",
              "correct_answer": "John Steinbeck ",
              "incorrect_answers": ["George Orwell", "Mark Twain ", "Harper Lee"]},
             {"category": "History", "type": "multiple", "difficulty": "medium",
              "question": "Adolf Hitler was born on which date?",
              "correct_answer": "April 20, 1889",
              "incorrect_answers": ["June 12, 1889", "February 6, 1889", "April 16, 1889"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
              "question": "What was the first PlayStation game to require the use of the DualShock controller?",
              "correct_answer": "Ape Escape",
              "incorrect_answers": ["Metal Gear", "Tekken ", "Tomba 2!"]},
             {"category": "History", "type": "multiple", "difficulty": "medium",
              "question": "What nationality was sultan Saladin?", "correct_answer": "Kurdish",
              "incorrect_answers": ["Arab", "Egyptian", "Syrian"]},
             {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
              "difficulty": "hard",
              "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
              "question": "In the Netflix show, Stranger Things, what song would Will sing to himself as he was missing?",
              "correct_answer": "Should I Stay or Should I Go?",
              "incorrect_answers": ["Love Will Tear Us Apart", "This Charming Man", "Africa"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
              "question": "In the video game &quot;Team Fortress 2&quot;, which class is able to double jump?",
              "correct_answer": "Scout", "incorrect_answers": ["Spy", "Engineer", "Pyro"]},
             {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
              "question": "The Windows 7 operating system has six main editions.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Politics", "type": "boolean", "difficulty": "medium",
              "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "History", "type": "boolean", "difficulty": "medium",
              "question": "The Hundred Years&#039; War was fought for more than a hundred years.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Sports", "type": "boolean", "difficulty": "easy",
              "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
              "question": "When was Left 4 Dead 2 released?", "correct_answer": "November 17, 2009",
              "incorrect_answers": ["May 3, 2008", "November 30, 2009", "June 30, 2010"]},
             {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
              "question": "Like his character in &quot;Parks and Recreation&quot;, Aziz Ansari was born in South Carolina.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Celebrities", "type": "multiple", "difficulty": "medium",
              "question": "How much weight did Chris Pratt lose for his role as Star-Lord in &quot;Guardians of the Galaxy&quot;?",
              "correct_answer": "60 lbs", "incorrect_answers": ["30 lbs", "50 lbs", "70 lbs"]},
             {"category": "Science: Mathematics", "type": "multiple", "difficulty": "easy",
              "question": "What is the symbol for Displacement?", "correct_answer": "&Delta;r",
              "incorrect_answers": ["dr", "Dp", "r"]},
             {"category": "Animals", "type": "multiple", "difficulty": "hard",
              "question": "Which species is a &quot;mountain chicken&quot;?",
              "correct_answer": "Frog", "incorrect_answers": ["Chicken", "Horse", "Fly"]},
             {"category": "Geography", "type": "multiple", "difficulty": "medium",
              "question": "Where is the &quot;Sonoran Desert&quot; located?",
              "correct_answer": "North America",
              "incorrect_answers": ["South America", "Asia", "Africa"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
              "question": "In the &quot;PAYDAY&quot; series, what is the real name of the character known as &quot;Dallas&quot;?",
              "correct_answer": "Nathan Steele",
              "incorrect_answers": ["Nate Siemens", "Nick Stamos", "Nolan Stuhlinger"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
              "question": "In &quot;Call Of Duty: Zombies&quot;, what does the game traditionally reward you for completing a boss round?",
              "correct_answer": "Max Ammo",
              "incorrect_answers": ["A Pack-A-Punched gun", "Death Machine", "Monkey Bombs"]},
             {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
              "question": "What is the name of the main antagonists in Battlestar Galactica?",
              "correct_answer": "The Cylons",
              "incorrect_answers": ["The Collective", "The Federation", "The Rebels"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
              "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "hard",
              "question": "When Magic: The Gathering was first solicited, which of the following was it originally titled?",
              "correct_answer": "Mana Clash",
              "incorrect_answers": ["Magic", "Magic Clash", "Mana Duels"]},
             {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
              "question": "Named after the mallow flower, mauve is a shade of what?",
              "correct_answer": "Purple", "incorrect_answers": ["Red", "Brown", "Pink"]},
             {"category": "Mythology", "type": "multiple", "difficulty": "medium",
              "question": "Who is the god of war in Polynesian mythology?",
              "correct_answer": "&#039;Oro", "incorrect_answers": ["Hina", "Kohara", "M\u0101ui"]},
             {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
              "question": "In Game of Thrones what is the name of Jon Snow&#039;s sword?",
              "correct_answer": "Longclaw",
              "incorrect_answers": ["Oathkeeper", "Widow&#039;s Wail", "Needle"]},
             {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
              "question": "What TV show is about a grandfather dragging his grandson around on adventures?",
              "correct_answer": "Rick &amp; Morty",
              "incorrect_answers": ["Family Guy", "South Park", "American Dad"]},
             {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
              "question": "What is the name of NASA&rsquo;s most famous space telescope?",
              "correct_answer": "Hubble Space Telescope",
              "incorrect_answers": ["Big Eye", "Death Star", "Millenium Falcon"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
              "question": "Which Final Fantasy game consisted of a female-only cast of party members?",
              "correct_answer": "Final Fantasy X-2",
              "incorrect_answers": ["Final Fantasy IX", "Final Fantasy V", "Final Fantasy XIII-2"]},
             {"category": "Mythology", "type": "multiple", "difficulty": "medium",
              "question": "The Norse god Odin has two pet crows named &quot;Huginn&quot; and &quot;Muninn&quot;.  What do their names mean?",
              "correct_answer": "Thought &amp; Memory",
              "incorrect_answers": ["Power &amp; Peace", "War &amp; Learning",
                                    "Sleeping &amp; Waking"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
              "question": "Which of the following are cells of the adaptive immune system?",
              "correct_answer": "Cytotoxic T cells",
              "incorrect_answers": ["Dendritic cells", "Natural killer cells",
                                    "White blood cells"]},
             {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
              "question": "Psych-Horror &quot;Eternal Darkness: Sanity&#039;s Requiem&quot;, developed by Silicon Knights in 2002, was published by who and on what platform?",
              "correct_answer": "Nintendo&reg; Co. Ltd. | GameCube&trade;", "incorrect_answers": [
                 "Sony&reg; Computer Entertainment&trade; Inc. | PlayStation&reg; 2",
                 "Microsoft&reg; Game Studios&trade; | XBox&trade;",
                 "Sega&reg; Enterprises Co. Ltd. | Dreamcast&trade;"]},
             {"category": "Geography", "type": "multiple", "difficulty": "medium",
              "question": "Which of these American cities has fewer than 1,000,000 people?",
              "correct_answer": "San Francisco, California",
              "incorrect_answers": ["Phoenix, Arizona", "San Antonio, Texas",
                                    "Philadelphia, Pennsylvania"]},
             {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
              "question": "The 1996 film &#039;Fargo&#039; is primarily set in which US state?",
              "correct_answer": "Minnesota",
              "incorrect_answers": ["North Dakota", "South Dakota", "Wisconsin"]},
             {"category": "Sports", "type": "multiple", "difficulty": "hard",
              "question": "The AHL affiliate team of the Boston Bruins is named what?",
              "correct_answer": "Providence Bruins",
              "incorrect_answers": ["New Haven Bruins", "Cambridge Bruins", "Hartford Bruins"]},
             {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
              "question": "In the Mad Max franchise, what type of car is the Pursuit Special driven by Max?",
              "correct_answer": "Ford Falcon",
              "incorrect_answers": ["Holden Monaro", "Chrysler Valiant Charger",
                                    "Pontiac Firebird"]},
             {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
              "question": "What are the three starter Pokemon available in Pokemon Black and White?",
              "correct_answer": "Snivy, Tepig, Oshawott",
              "incorrect_answers": ["Snivy, Fennekin, Froakie", "Chespin, Tepig, Froakie",
                                   # "Chespin, Fennekin, Oshawott""""
